language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: nosetests --with-coverage --cover-package=pssh tests
notifications:
  email:
    on_failure: change
after_success:
  pip install coveralls
  coveralls
